version: '3.8'

networks:
  loki:

volumes:
  consul_config:
  consul_data:

services:
  consul:
    image: consul:${CONSUL_VERSION}
    hostname: consul
    restart: always
    networks:
      loki:
    # ports:
    #   - '8500:8500'
    volumes:
      - type: volume
        source: consul_config
        target: /consul/config
      - type: volume
        source: consul_data
        target: /consul/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      restart_policy:
        condition: any
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command:
      - agent
      - -server
      - -datacenter=cortex
      - -bootstrap-expect=1
      - -client=0.0.0.0
      - -ui
      - -data-dir=/consul/data
      - -config-dir=/consul/config

  loki:
    image: grafana/loki:${LOKI_VERSION}
    hostname: loki
    restart: always
    networks:
      loki:
    ports:
      - '3100:3100'
    volumes:
      - type: bind
        source: ${PWD}/config/loki-config.yml
        target: /etc/loki-config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    command:
      - -config.file=/etc/loki-config.yml
