name: thingsboard

services:
  tb:
    image: ${TB_IMAGE}
    restart: always
    ports:
    - 9090:9090                # Internal HTTP
    - 1883:1883                # Internal MQTT
    - 7070:7070                # Internal Edge RPC
    - 5683-5688:5683-5688/udp  # Internal COAP and LwM2M
    environment:
      TB_QUEUE_TYPE: in-memory
    # volumes:
    # - ${PWD}/tb-data:/data
    # - ${PWD}/tb-logs:/var/log/thingsboard
