name: thingsboard

services:
  tb:
    image: ${TB_IMAGE}:${TB_TAG}
    restart: always
    ports:
    - 8080:9090                # Internal HTTP
    - 1883:1883                # Internal MQTT
    - 7070:7070                # Internal Edge RPC
    - 5683-5688:5683-5688/udp  # Internal COAP and LwM2M
    environment:
      TB_QUEUE_TYPE: in-memory
    # volumes:
    # - type: bind
    #   source: ${PWD}/tb-data
    #   target: /data
    # - type: bind
    #   source: ${PWD}/tb-logs
    #   target: /var/log/thingsboard
