configs:
  ssl_config:
    content: |
      <!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure_10_0.dtd">
      <Configure id="Server" class="io.cloudbeaver.server.jetty.CBJettyServer$$JettyServer">
          <New id="httpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
              <Set name="sendServerVersion">false</Set>
              <Set name="sendDateHeader">false</Set>
          </New>

          <Call name="addBean">
              <Arg>
                  <New id="sslContextFactory" class="org.eclipse.jetty.util.ssl.SslContextFactory$$Server">
                      <Set name="keyStorePath">
                          ${KEY_STORE_PATH}
                      </Set>
                      <Set name="keyStorePassword">
                          ${KEY_STORE_PASSWORD}
                      </Set>
                      <Set name="trustStorePath">
                          ${TRUST_STORE_PATH}
                      </Set>
                      <Set name="trustStorePassword">
                          ${TRUST_STORE_PASSWORD}
                      </Set>
                      <Set name="IncludeProtocols">
                          <Array type="String">
                              <Item>TLSv1.2</Item>
                          </Array>
                      </Set>
                      <Set name="IncludeCipherSuites">
                          <Array type="String">
                              <Item>TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384</Item>
                              <Item>TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384</Item>
                          </Array>
                      </Set>
                      <New id="tlsHttpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
                          <Arg>
                              <Ref refid="httpConfig"/>
                          </Arg>
                          <Call name="addCustomizer">
                              <Arg>
                                  <New class="org.eclipse.jetty.server.SecureRequestCustomizer">
                                      <Set name="sniHostCheck">false</Set>
                                  </New>
                              </Arg>
                          </Call>
                      </New>
                  </New>
              </Arg>
          </Call>

          <Call id="sslConnector" name="addConnector">
              <Arg>
                  <New class="org.eclipse.jetty.server.ServerConnector">
                      <Arg name="server">
                          <Ref refid="Server"/>
                      </Arg>
                      <Arg name="factories">
                          <Array type="org.eclipse.jetty.server.ConnectionFactory">
                              <Item>
                                  <New class="org.eclipse.jetty.server.SslConnectionFactory">
                                      <Arg name="next">http/1.1</Arg>
                                      <Arg name="sslContextFactory">
                                          <Ref refid="sslContextFactory"/>
                                      </Arg>
                                  </New>
                              </Item>
                              <Item>
                                  <New class="org.eclipse.jetty.server.HttpConnectionFactory">
                                      <Arg name="config">
                                          <Ref refid="tlsHttpConfig"/>
                                      </Arg>
                                  </New>
                              </Item>
                          </Array>
                      </Arg>
                      <Set name="port">
                          8978
                      </Set>
                      <Set name="idleTimeout">
                          <Property name="jetty.idleTimeout" default="30000"/>
                      </Set>
                  </New>
              </Arg>
          </Call>
      </Configure>
  nginx_conf:
    content: |
      user nginx;
      worker_processes 1;
      error_log /var/log/nginx/error.log warn;
      pid /var/run/nginx.pid;
      events {
        worker_connections 1024;
      }
      http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        log_format main '$$remote_addr - $$remote_user [$$time_local] "$$request" '
                        '$$status $$body_bytes_sent "$$http_referer" '
                        '"$$http_user_agent" "$$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log  main;
        sendfile on;
        keepalive_timeout 65;
        server {
          listen 8080 ssl;
          server_name localhost;
          ssl_certificate     /etc/nginx/cert/server.crt;
          ssl_certificate_key /etc/nginx/cert/server.key;
          ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
          ssl_ciphers         HIGH:!aNULL:!MD5;

          location / {
            proxy_pass       http://dbeaver:8978;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;
            proxy_set_header Host $$http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $$http_upgrade;
            proxy_set_header Connection "upgrade";
          }
          error_page 500 502 503 504 /50x.html;
          location = /50x.html {
            root /usr/share/nginx/html;
          }
        }
      }
  server_crt:
    content: |
      -----BEGIN CERTIFICATE-----
      Place the server certificate here
      -----END CERTIFICATE-----
  server_key:
    content: |
      -----BEGIN PRIVATE KEY-----
      Place the server private key here
      -----END PRIVATE KEY-----
