target: "all"

auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

distributor:
  ring:
    kvstore:
      store: consul
      prefix: collectors/
      consul:
        host: consul:8500
    heartbeat_timeout: 1m

ingester:
  wal:
    enabled: true
    dir: /loki/wal
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  max_transfer_retries: 0
  lifecycler:
    join_after: 10s
    observe_period: 10s
    min_ready_duration: 0s
    final_sleep: 5s
    num_tokens: 512
    ring:
      kvstore:
        store: consul
        prefix: collectors/
        consul:
          host: consul:8500
      replication_factor: 1

schema_config:
  configs:
    - from: 2022-01-01
      store: aws
      object_store: aws
      schema: v11
      index:
        prefix: loki_index_
        period: 0
        # period: 24h
        tags:
          owner: MBSD
          purpose: Loki

storage_config:
  aws:
    s3: s3://{access_key}@us-east-1/mbsd-loki
    dynamodb:
      dynamodb_url: dynamodb://{access_key}@us-east-1

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

ruler:
  # external_url:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  enable_sharding: true
  ring:
    kvstore:
      store: consul
      prefix: rulers/
      consul:
        host: consul:8500
