version: "3.8"

services:
  alpine:
    image: netopeer2:alpine
    build:
      context: .
      dockerfile: ./Dockerfile.alpine
      args:
        LIBYANG_VERSION: ${LIBYANG_VERSION}
        LIBNETCONF2_VERSION: ${LIBNETCONF2_VERSION}
        SYSREPO_VERSION: ${SYSREPO_VERSION}
        NETOPEER2_VERSION: ${NETOPEER2_VERSION}
        CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}
        CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}
        SYSREPO_GROUP: ${SYSREPO_GROUP}
        SYSREPO_UMASK: ${SYSREPO_UMASK}
        ENABLE_TLS: ${ENABLE_TLS}
        ENABLE_SSH: ${ENABLE_SSH}
        ENABLE_DNSSEC: ${ENABLE_DNSSEC}
        BUILD_CLI: ${BUILD_CLI}
        NETOPEER2_USER: ${NETOPEER2_USER}
        NETOPEER2_PASSWD: ${NETOPEER2_PASSWD}
    hostname: np2-alpine
    command: ash

  ubuntu:
    image: netopeer2:ubuntu
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu
      args:
        LIBYANG_VERSION: ${LIBYANG_VERSION}
        LIBNETCONF2_VERSION: ${LIBNETCONF2_VERSION}
        SYSREPO_VERSION: ${SYSREPO_VERSION}
        NETOPEER2_VERSION: ${NETOPEER2_VERSION}
        CMAKE_INSTALL_PREFIX: ${CMAKE_INSTALL_PREFIX}
        CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}
        SYSREPO_GROUP: ${SYSREPO_GROUP}
        SYSREPO_UMASK: ${SYSREPO_UMASK}
        ENABLE_TLS: ${ENABLE_TLS}
        ENABLE_SSH: ${ENABLE_SSH}
        ENABLE_DNSSEC: ${ENABLE_DNSSEC}
        BUILD_CLI: ${BUILD_CLI}
        NETOPEER2_USER: ${NETOPEER2_USER}
        NETOPEER2_PASSWD: ${NETOPEER2_PASSWD}
    hostname: np2-ubuntu
    command: bash
