version: "3.8"

services:
  alpine:
    image: ueransim:alpine
    build:
      context: .
      dockerfile: ./Dockerfile.alpine
    cap_add:
    - NET_ADMIN
    devices:
    - "/dev/net/tun"
    command: ash

  ubuntu:
    image: ueransim:ubuntu
    build:
      context: .
      dockerfile: ./Dockerfile.ubuntu
    cap_add:
    - NET_ADMIN
    devices:
    - "/dev/net/tun"
    command: bash
