global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: 'Daniel'
    __tenant__: 'World'
    cluster: 'Islands'
    __replica__: 'replica2'

remote_write:
# - url: http://cortex:9001/api/v1/push
- url: http://cortex:9010/push

scrape_configs:
- job_name: 'Islands'
  static_configs:
  - targets:
    - GreenIsland:9100
