FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Install Mosquitto MQTT broker
RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y mosquitto mosquitto-clients && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 1883 8883

# ENTRYPOINT ["/usr/sbin/mosquitto"]
