#!/bin/bash

SERVICES=(amf ausf bsf hss mme nrf nssf pcf pcrf scp sgwc sgwu smf udm udr upf)

AMF_NGAP_ADDR=127.0.0.5
UPF_GTPU_ADDR=127.0.0.7

function mongodb_start {
  if [ $(ps aux | grep mongod | grep -v grep | wc -l) -eq 0 ]; then
    /usr/bin/mongod --config /etc/mongod.conf &
    sleep 5
  fi
}

# tun iface create
function tun_create {
  if ! grep "ogstun" /proc/net/dev > /dev/null; then
    echo "Creating ogstun device"
    ip tuntap add name ogstun mode tun
  fi

  ip addr del ${IPV4_TUN_ADDR} dev ogstun 2> /dev/null || true
  ip addr add ${IPV4_TUN_ADDR} dev ogstun

  # sysctl -w net.ipv6.conf.all.disable_ipv6=0
  ip addr del ${IPV6_TUN_ADDR} dev ogstun 2> /dev/null || true
  ip addr add ${IPV6_TUN_ADDR} dev ogstun

  ip link set ogstun up

  # sysctl -w net.ipv4.ip_forward=1
  # if [ "${ENABLE_NAT}" = true ] ; then
  #   iptables -t nat -A POSTROUTING -s ${IPV4_TUN_SUBNET} ! -o ogstun -j MASQUERADE;
  # fi
}

function open5gs_start {
  #
  # TODO: Customize the address of amf ngap and upf gtpu
  #

  for service in ${SERVICES[@]}; do
    echo "Start ${service}"
    /usr/bin/open5gs-${service}d -c /etc/open5gs/${service}.yaml &
  done
}

tun_create
mongodb_start
open5gs_start
