version: '3.8'
services:
  registry-nossl:
    image: registry:2.7
    deploy:
      mode: replicated  # replicated | global
      replicas: 1
      placement:
        constraints:
          - node.role == manager  # manager | worker
      restart_policy:
        condition: any  # none | on-failure | any(default)
    networks:
      - ocarina
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: ./registry
        target: /var/lib/registry

  registry:
    image: registry:2.7
    deploy:
      mode: replicated  # replicated | global
      replicas: 1
      placement:
        constraints:
          - node.role == manager  # manager | worker
      restart_policy:
        condition: any  # none | on-failure | any(default)
    networks:
      - ocarina
    ports:
      - '443:443'
    volumes:
      - type: bind
        source: ./certs
        target: /certs
      - type: bind
        source: ./registry
        target: /var/lib/registry
      # - type: volume
      #   source: registry
      #   target: /var/lib/registry
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:443
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/ocarina.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/ocarina.key

  visualizer:
    image: dockersamples/visualizer:stable
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - '8080:8080'
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - ocarina

# volumes:
#   registry:

networks:
  ocarina:

