version: "3.8"

services:
  open5gs:
    image: open5gs:latest
    hostname: open5gs
    build:
      context: .
      dockerfile: ./Dockerfile
    cap_add:
    - NET_ADMIN
    devices:
    - '/dev/net/tun'
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.ip_forward: 1
    ports:
    - 38412:38412/sctp
    - 2152:2152/udp
    - 3000:3000/tcp
    environment:
      ENABLE_NAT: 'true'
      NODE_ENV: production
      UPF_GTPU_ADVERTISE:
      MCC: 999
      MNC: 70
