#!/bin/bash

if [ -n "$(docker container ls --filter name=open5gs --quiet)" ]; then
  echo -e "\e[32mAttach to \e[33mOpen5GS \e[32mcontainer\e[39m"
  docker container attach open5gs
else
  echo -e "\e[32mStart \e[33mOpen5GS \e[32mcontainer\e[39m"
  docker container run --rm -it \
                       --name open5gs \
                       --hostname open5gs \
                       --cap-add NET_ADMIN \
                       --device /dev/net/tun \
                       --sysctl 'net.ipv6.conf.all.disable_ipv6=0' \
                       --sysctl 'net.ipv4.ip_forward=1' \
                       --env ENABLE_NAT=true \
                       --env NODE_ENV=production \
                       --env UPF_GTPU_ADVERTISE= \
                       --env MCC=999 \
                       --env MNC=70 \
                       --publish 38412:38412/sctp \
                       --publish 2152:2152/udp \
                       --publish 3000:3000/tcp \
                       --volume ${PWD}:/home/host \
                       open5gs bash
fi
