#!/bin/bash

# Required
domain=ocarina


# Change to your company details
country=TW
state=Taiwan
locality=Taipei
organization=ocarina.com
organizationalunit=DevOps
email=galoistsai@gmail.com
commonname=ocarina

# Generate the private key and certificate in just one line
#openssl req -newkey rsa:4096 -nodes -sha256 -keyout $domain.key -x509 -days 365 -out $domain.crt \
#    -subj "//C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email"

# Optional
password=$(head -c 500 /dev/urandom | tr -dc a-z0-9A-Z | head -c 128; echo)

if [ -z "$domain" ]
then
    echo "Argument not present."
    echo "Usage $0 [common name]"

    exit 99
fi

echo "Generating key request for $domain"

# Generate a RSA private key
echo "Generate a RSA private key with passphrase"
openssl genrsa -des3 -passout pass:$password -out $domain.key 4096 -noout

# Remove passphrase from the RSA private key. Comment the line out to keep the passphrase
echo "Removing passphrase from the RSA private key"
openssl rsa -in $domain.key -passin pass:$password -out $domain.key


# Create the CSR (Certificate Signing Request)
echo "Creating the CSR (Certificate Signing Request)"
openssl req -new -key $domain.key -out $domain.csr -passin pass:$password \
    -subj "//C=$country/ST=$state/L=$locality/O=$organization/OU=$organizationalunit/CN=$commonname/emailAddress=$email"


# Generate the X.509 Certificate (good for 1 years)
echo "Generate the X.509 Certificate"
openssl x509 -req -days 365 -in $domain.csr -signkey $domain.key -out $domain.crt

