ARG DISTRO_VERSION=22.04
FROM ubuntu:${DISTRO_VERSION}

# Install supervisor
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y supervisor && \
    rm -rf /var/lib/apt/lists/*

# Copy the configuration file
# COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY supervisord.conf /etc/supervisord.conf

# Run the process manager
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
